"""Type stubs for biblioteca.estruturas package"""
from typing import Union

class CMSCU:
    def __init__(self, largura: int, profundidade: int, seed: int) -> None: ...
    @staticmethod
    def criar_apartir_erro_esperado(deviation: float, error: float, seed: int) -> CMSCU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CMSCU: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CML8SCU:
    def __init__(self, largura: int, profundidade: int, base: float, seed: int) -> None: ...
    # @staticmethod
    # def criar_apartir_erro_esperado(deviation: float, error: float, base: float, seed: int) -> CML8SCU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CML8SCU: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> float: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CML8HSCU:
    def __init__(self, largura: int, profundidade: int, camadas_lineares: int, base: float, seed: int) -> None: ...
    # @staticmethod
    # def criar_apartir_erro_esperado(deviation: float, error: float, base: float, seed: int) -> CML8HSCU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CML8HSCU: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> float: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CL:
    def __init__(self, largura: int, profundidade: int, expansao: int, modo: int, seed: int) -> None: ...
    # @staticmethod
    # def criar_apartir_erro_esperado(deviation: float, error: float, base: float, seed: int) -> CML8SCU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CL: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CMTS:
    def __init__(self, largura: int, profundidade: int, base_arvore: int, seed: int) -> None: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CMTS: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...
    def debug(self) -> dict: ...

__all__ = ["CMSCU", "CML8SCU", "CML8HSCU", "CL", "CMTS"]