"""Type stubs for biblioteca.estruturas package"""
from typing import Union

class CMSCU:
    def __init__(self, largura: int, profundidade: int, seed: int) -> None: ...
    @staticmethod
    def criar_apartir_erro_esperado(deviation: float, error: float, seed: int) -> CMSCU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CMSCU: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CMLS8CU:
    def __init__(self, largura: int, profundidade: int, base: float, seed: int) -> None: ...
    # @staticmethod
    # def criar_apartir_erro_esperado(deviation: float, error: float, base: float, seed: int) -> CMLS8CU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CMLS8CU: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> float: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CMLS8CUH:
    def __init__(self, largura: int, profundidade: int, camadas_lineares: int, base: float, seed: int) -> None: ...
    # @staticmethod
    # def criar_apartir_erro_esperado(deviation: float, error: float, base: float, seed: int) -> CMLS8CU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CMLS8CUH: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> float: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CL:
    def __init__(self, largura: int, profundidade: int, expansao: int, modo: int, seed: int) -> None: ...
    # @staticmethod
    # def criar_apartir_erro_esperado(deviation: float, error: float, base: float, seed: int) -> CMLS8CU: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CL: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...

class CMTS:
    def __init__(self, largura: int, profundidade: int, base_arvore: int, seed: int) -> None: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CMTS: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...
    def debug(self) -> dict: ...

class CTL:
    def __init__(self, largura: int, profundidade: int, expansao: int, base_arvore: int, seed: int) -> None: ...
    @staticmethod
    def carregar(nome_arquivo: str) -> CTL: ...
    def incrementar(self, elemento: Union[str, bytes]) -> None: ...
    def estimar(self, elemento: Union[str, bytes]) -> int: ...
    def sizeof(self) -> int: ...
    def memoria(self) -> dict: ...
    def salvar(self, nome_arquivo: str) -> None: ...
    def debug(self) -> dict: ...

__all__ = ["CMSCU", "CMLS8CU", "CMLS8CUH", "CL", "CMTS", "CTL"]
